### ISSUE TITLE
Will be this in the future an option for Onedrive non Office 365 users?

### ISSUE THREAD

**Issue by juanpaexpedite** [microsoftgraph/uwp-csharp-excel-snippets-rest-sample#2]
There are free alternatives to connect to online spreadsheets that even have a database alike API, and this  just to start needs an Office 365 account, so why not leave the Windows 10 users access to their Excel files in onedrive without so many restrictions. 

Why? Because at the moment there is no option to synchronize real data among devices in a P2P mode. Even SQLite core it has no sync option, no encryption, no protection. So IMHO everything is not a SOLID solution and if they are even restricted how they are going to be used widely?

**Comment by jakobpn** [comment]
Hi Juan, thanks for your feedback. You correct that the Microsoft Graph API currently requires the user to have an Office 365 account. It is in our backlog to provide access using a Microsoft Account and access to Excel workbooks on OneDrive.

**Comment by juanpaexpedite** [comment]
I really appreciate the answer. When it get released I want to create (in case it is not implemented) a CRUD layer. Hope it get released this year,

Thank you
