### ISSUE TITLE
Log-In Confusion

### ISSUE THREAD

**Issue by prettyextreme** [microsoftgraph/uwp-csharp-excel-snippets-rest-sample#5]
When I run the app and try to log in with my Microsoft account, (I'm a Microsoft employee, so I'm pretty sure I have Office 365 Business,) this example app tells me the following:

Message: AADSTS90094: An administrator of Microsoft has set a policy that prevents you from granting ExcelRESTApiExplorer the permissions it is requesting. Contact an administrator of Microsoft who can grant permissions to this application on your behalf.

I’d have thought that I was trying to connect to some kind of Sharepoint endpoint, but it’s unclear. Is “ExcelRESTApiExplorer” an Azure Active Directory App? Some other app? Do I need to get permission from someone to run this example? The readme didn’t hint at anything of the sort. Any ideas?

**Comment by jakobpn** [comment]
Followed up offline since this is related to a Microsoft specific configuration.
